In [2]:
import numpy as np
import pandas as pd


In [3]:
dataset = pd.read_csv("weatherAUS.csv")
dataset.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  01-12-2008   Albury     13.4     22.9       0.6          NaN       NaN   
1  02-12-2008   Albury      7.4     25.1       0.0          NaN       NaN   
2  03-12-2008   Albury     12.9     25.7       0.0          NaN       NaN   
3  04-12-2008   Albury      9.2     28.0       0.0          NaN       NaN   
4  05-12-2008   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  

[5 rows x 23 columns]

In [4]:
X = dataset.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
y = dataset.iloc[:,-1].values

In [5]:
X

array([['Albury', 13.4, 22.9, ..., 16.9, 21.8, 'No'],
       ['Albury', 7.4, 25.1, ..., 17.2, 24.3, 'No'],
       ['Albury', 12.9, 25.7, ..., 21.0, 23.2, 'No'],
       ...,
       ['Uluru', 5.4, 26.9, ..., 12.5, 26.1, 'No'],
       ['Uluru', 7.8, 27.0, ..., 15.1, 26.0, 'No'],
       ['Uluru', 14.9, nan, ..., 15.0, 20.9, 'No']], dtype=object)

In [6]:
y = y.reshape(-1,1)

In [7]:
y

array([['No'],
       ['No'],
       ['No'],
       ...,
       ['No'],
       ['No'],
       [nan]], dtype=object)

## dealing with missing values

In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
X = imputer.fit_transform(X)
y = imputer.fit_transform(y)


## label Encoding

In [9]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
X[:,0] = le1.fit_transform(X[:,0])

le2 = LabelEncoder()
X[:,4] = le2.fit_transform(X[:,4])

le3 = LabelEncoder()
X[:,6] = le3.fit_transform(X[:,6])

le4 = LabelEncoder()
X[:,7] = le4.fit_transform(X[:,7])

le5 = LabelEncoder()
X[:,-1] = le5.fit_transform(X[:,-1])

le6 = LabelEncoder()
y = le6.fit_transform(y)


c:\Users\amarn\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## correlation

In [10]:
corr_matrix = dataset.corr()
corr_matrix['Humidity3pm'].sort_values(ascending=False)

Humidity3pm      1.000000
Humidity9am      0.666949
Cloud3pm         0.523120
Cloud9am         0.517120
Rainfall         0.255755
Pressure3pm      0.051997
WindSpeed3pm     0.016432
MinTemp          0.006089
WindGustSpeed   -0.026327
Pressure9am     -0.027544
WindSpeed9am    -0.031614
Temp9am         -0.221019
Evaporation     -0.390243
MaxTemp         -0.508855
Temp3pm         -0.557841
Sunshine        -0.629130
Name: Humidity3pm, dtype: float64

## feature scaling

In [11]:
from sklearn.preprocessing import StandardScaler
stsc = StandardScaler()
X = stsc.fit_transform(X)

In [12]:
print(X)

[[-1.53166617  0.19132753 -0.04135977 ... -0.01407077  0.02310362
  -0.52979545]
 [-1.53166617 -0.75105231  0.26874452 ...  0.03244663  0.387799
  -0.52979545]
 [-1.53166617  0.11279588  0.35331842 ...  0.62166712  0.22733303
  -0.52979545]
 ...
 [ 1.20928479 -1.06517892  0.52246622 ... -0.69632607  0.65037966
  -0.52979545]
 [ 1.20928479 -0.68822699  0.53656187 ... -0.29317521  0.63579185
  -0.52979545]
 [ 1.20928479  0.42692249 -0.45013361 ... -0.30868102 -0.10818671
  -0.52979545]]


## splitting dataset

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

## Model selection - classification

In [14]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=150, random_state=0)
clf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=150, random_state=0)

In [15]:
clf.score(X_train,y_train)

0.9998968788670425

In [16]:
X_test[1]

array([ 0.92816162,  0.14420854,  0.50837057, -0.27509664,  1.04522847,
       -0.35504254,  1.32876628,  1.36645776,  0.90308937, -0.40476401,
       -0.43724173, -1.44365196, -0.67077348, -0.93944788, -2.10110212,
       -1.86680901, -0.01407077,  0.62120403, -0.52979545])

In [17]:
features = [[-0.12605029,  0.44262882, -0.60518576,  0.2255147 , -0.44600721,
        1.08637965, -0.2213385 , -0.1760315 ,  1.12835936,  1.42289395,
        0.18513892,  0.60800336, -1.82817847, -1.7347704 , -0.55281181,
       -0.21697586,  0.04795243, -0.5895846 ,  1.88752093]]

In [18]:
y_pred = clf.predict(X_test)

In [19]:
y_pred

array([1, 0, 0, ..., 0, 1, 0])

In [20]:
y_test

array([1, 0, 0, ..., 0, 0, 0])

In [21]:
y_pred = le6.inverse_transform(y_pred)
y_test = le6.inverse_transform(y_test)

In [22]:
print(f"P: {y_pred}\t A: {y_test}")

P: ['Yes' 'No' 'No' ... 'No' 'Yes' 'No']	 A: ['Yes' 'No' 'No' ... 'No' 'No' 'No']


In [23]:
y_pred = y_pred.reshape(-1,1)
y_test = y_test.reshape(-1,1)


In [24]:
df = np.concatenate((y_test,y_pred),axis=1)

In [25]:
df1 = pd.DataFrame(df,columns=['Rain on tomorrow','Prediction'])

In [26]:
df1.head()

Rain on tomorrow Prediction
0              Yes        Yes
1               No         No
2               No         No
3               No         No
4               No        Yes

In [27]:
df1.to_csv("test_result.csv",index = False)

## calculating accuracy

In [28]:
from sklearn.metrics import accuracy_score
print(f"The accuracy of the model is : {(accuracy_score(y_test,y_pred))*100} %")

The accuracy of the model is : 85.1024336587378 %


## saving the model

In [29]:
from joblib import dump
dump(clf,"launchedmodel.joblib")

['launchedmodel.joblib']